routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', [\App\Http\Controllers\CarBrandController::class, 'index'])->name('index');
Route::get('/car-models', [\App\Http\Controllers\CarModelController::class, 'index'])->name('car-models');

Route::resource('cars', \App\Http\Controllers\CarController::class);

app/Models/Car.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * @property int $id Идентификатор записи
 * @property int $year Год выпуска
 * @property int $mileage Пробег
 * @property string $color Цвет
 * @property-read Carbon $created_at Дата создания
 * @property-read Carbon $updated_at Дата обновления
 *
 * @property-read CarModel $carModel
 */
class Car extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'year',
        'mileage',
        'color',
    ];


    /**
     * Get the car model that owns the car.
     */
    public function carModel(): BelongsTo
    {
        return $this->belongsTo(CarModel::class);
    }
}

app/Models/CarBrand.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * @property int $id Идентификатор записи
 * @property string $name Название
 * @property-read Carbon $created_at Дата создания
 * @property-read Carbon $updated_at Дата обновления
 */
class CarBrand extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
    ];


    /**
     * Get the car models for the car brand.
     */
    public function carModels(): HasMany
    {
        return $this->hasMany(CarModel::class);
    }
}

app/Models/CarModel.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * @property int $id Идентификатор записи
 * @property string $name Название
 * @property-read Carbon $created_at Дата создания
 * @property-read Carbon $updated_at Дата обновления
 *
 * @property-read CarBrand $carBrand
 */
class CarModel extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
    ];


    /**
     * Get the car brand that owns the car model.
     */
    public function carBrand(): BelongsTo
    {
        return $this->belongsTo(CarBrand::class);
    }


    /**
     * Get the cars for the car model.
     */
    public function cars(): HasMany
    {
        return $this->hasMany(Car::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CarBrandController.php
<?php

namespace App\Http\Controllers;

use App\Models\CarBrand;

class CarBrandController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $carBrands = CarBrand::query()->latest()->paginate(10);
        return view('index', compact('carBrands'));
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CarRequest;
use App\Models\Car;
use App\Models\CarBrand;
use App\Models\CarModel;
use Illuminate\Support\Arr;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $cars = Car::query()->latest()->paginate(4);
        return view('cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $carBrands = CarBrand::query()->get();
        $carModels = CarModel::query()->get();

        return view('cars.create', compact(
            'carBrands',
            'carModels',
        ));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CarRequest $request)
    {
        $data = $request->validated();

        /** @var CarBrand $carBrand */
        $carBrand = CarBrand::query()->firstOrCreate([
            'id' => $data['car-brand']
        ]);
        /** @var CarModel $carModel */
        $carModel = $carBrand->carModels()->firstOrCreate([
            'id' => $data['car-model']
        ]);

        $carModel->cars()->create($data);

        $cars = Car::query()->latest()->paginate(4);
        return view('cars.index', compact('cars'))->with('success', 'Автомобиль добавлен');
    }

    /**
     * Display the specified resource.
     */
    public function show(Car $car)
    {
        return view('cars.show', compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Car $car)
    {
        $carBrands = CarBrand::query()->get();
        $carModels = CarModel::query()->get();

        return view('cars.edit', compact(
            'car',
            'carBrands',
            'carModels',
        ));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(CarRequest $request, Car $car)
    {
        $data = $request->validated();

        $car->update(Arr::only($data, [
            'year',
            'mileage',
            'color',
        ]));

        $car->carModel->update([
            'id' => $data['car-model']
        ]);

        $car->carModel->carBrand->update([
            'id' => $data['car-brand']
        ]);

        $carBrands = CarBrand::query()->get();
        $carModels = CarModel::query()->get();

        return view('cars.edit', compact(
            'car',
            'carBrands',
            'carModels',
        ))->with('success', 'Автомобиль обновлен');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Car $car)
    {
        $car->delete();
        $cars = Car::query()->latest()->paginate(4);
        return view('cars.index', compact('cars'))->with('success', 'Автомобиль удален');
    }
}

app/Http/Controllers/CarModelController.php
<?php

namespace App\Http\Controllers;

use App\Models\CarModel;

class CarModelController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $carModels = CarModel::query()->latest()->paginate(10);
        return view('car-models/index', compact('carModels'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/car-models/index.blade.php
@include('components.header')
<div class="p-4 m-4">
    <div class="body-container">
        <div class="container mb-5">
            <h1 class="display-6">Модели автомобилей</h1>
        </div>
        <div class="container">
            <div class="cars container overflow-hidden">
                @if($carModels->isEmpty())
                    <p class="label-show">Модели автомобилей</p>
                @else
                    @foreach($carModels as $carModel)
                        <div class="card text-center mb-3">
                            <div class="card-header">
                                Модель
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">{{ $carModel->name }}</h5>
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
        <div class="d-flex justify-content-center m-3">{!! $carModels->links() !!}</div>
    </div>
</div>
@include('components.footer')

resources/views/cars/create.blade.php
@include('components.header')
<div class="p-4 m-4">
    <div class="body-container">
        <div class="container mb-5">
            <h1 class="display-6">Создать карточку автомобиля</h1>
        </div>
        <div class="container">
            @include('components.messages')
            <form class="col-lg-9" action="{{ route('cars.store') }}" method="post">
                @csrf
                <div class="mb-3">
                    <label for="car-brand" class="form-label">Марка автомобиля</label>
                    <select class="form-control" aria-label="Введите марку автомобиля" id="car-brand" name="car-brand">
                        @foreach($carBrands as $carBrand)
                            <option value="{{ $carBrand->id }}">{{ $carBrand->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="car-model" class="form-label">Модель автомобиля</label>
                    <select class="form-control" aria-label="Введите модель автомобиля" id="car-model" name="car-model">
                        @foreach($carModels as $carModel)
                            <option value="{{ $carModel->id }}">{{ $carModel->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="year" class="form-label">Год выпуска</label>
                    <input type="number" class="form-control" id="year" name="year"
                           placeholder="Введите год выпуска">
                </div>
                <div class="mb-3">
                    <label for="mileage" class="form-label">Пробег</label>
                    <input type="number" class="form-control" id="mileage" name="mileage"
                           placeholder="Введите пробег">
                </div>
                <div class="mb-3">
                    <label for="color" class="form-label">Цвет автомобиля</label>
                    <input type="text" class="form-control" id="color" name="color"
                           placeholder="Введите цвет автомобиля">
                </div>
                <div class="mb-3 mt-3">
                    <button class="btn btn-success" role="button" type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>
@include('components.footer')

resources/views/cars/edit.blade.php
@include('components.header')
<div class="p-4 m-4">
    <div class="body-container">
        <div class="container mb-5">
            <h1 class="display-6">Редактировать карточку автомобиля</h1>
        </div>
        <div class="container">
            @include('components.messages')
            <form class="col-lg-9" action="{{ route('cars.update', $car) }}" method="post">
                @csrf
                @method('put')
                <div class="mb-3">
                    <label for="car-brand" class="form-label">Марка автомобиля</label>
                    <select class="form-control" aria-label="Введите марку автомобиля" id="car-brand" name="car-brand">
                        @foreach($carBrands as $carBrand)
                            <option @selected($car->CarModel->CarBrand->id === $carBrand->id)
                                    value="{{ $carBrand->id }}">{{ $carBrand->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="car-model" class="form-label">Модель автомобиля</label>
                    <select class="form-control" aria-label="Введите модель автомобиля" id="car-model" name="car-model">
                        @foreach($carModels as $carModel)
                            <option @selected($car->CarModel->id === $carModel->id)
                                    value="{{ $carModel->id }}">{{ $carModel->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="year" class="form-label">Год выпуска</label>
                    <input type="number" class="form-control" id="year" name="year"
                           placeholder="Введите год выпуска" value="{{ $car->year }}">
                </div>
                <div class="mb-3">
                    <label for="mileage" class="form-label">Пробег</label>
                    <input type="number" class="form-control" id="mileage" name="mileage"
                           placeholder="Введите пробег" value="{{ $car->mileage }}">
                </div>
                <div class="mb-3">
                    <label for="color" class="form-label">Цвет автомобиля</label>
                    <input type="text" class="form-control" id="color" name="color"
                           placeholder="Введите цвет автомобиля" value="{{ $car->color }}">
                </div>
                <div class="mb-3 mt-3">
                    <button class="btn btn-success" role="button" type="submit">Сохранить</button>
                </div>
            </form>
            <div class="col">
                <form action="{{ route('cars.destroy', $car) }}" method="post">
                    @csrf
                    @method('delete')
                    <button class="btn btn-dark" role="button" type="submit">
                        Удалить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
@include('components.footer')

resources/views/cars/index.blade.php
@include('components.header')
<div class="p-4 m-4">
    <div class="body-container">
        <div class="m-3">
            <div class="container mb-5">
                <h1 class="display-6">Автомобили</h1>
            </div>
            <div class="container">
                @include('components.messages')
                <div class="cars container overflow-hidden">
                    @if($cars->isEmpty())
                        <p class="label-show">Автомобили</p>
                        <a href="{{ route('cars.create') }}" class="btn btn-primary">Добавить автомобиль</a>
                    @else
                        <a href="{{ route('cars.create') }}" class="btn btn-success mb-5">Добавить автомобиль</a>
                        @foreach($cars as $car)
                            <div class="card text-center mb-3">
                                <div class="card-header">
                                    Автомобиль
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">{{ $car->carModel->carBrand->name }}</h5>
                                    <h5 class="card-title">{{ $car->carModel->name }}</h5>
                                    <p class="card-text">{{ $car->year }} год</p>
                                    <a href="{{ route('cars.show', $car) }}" class="btn btn-secondary">Подробнее</a>
                                </div>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
            <div class="d-flex justify-content-center m-3">{!! $cars->links() !!}</div>
        </div>
    </div>
</div>
@include('components.footer')

resources/views/cars/show.blade.php
@include('components.header')
<div class="p-4 m-4">
    <div class="body-container">
        <div class="container mb-5">
            <h1 class="display-6">Автомобиль</h1>
        </div>
        <div class="container">
            <form class="col-lg-9">
                <fieldset disabled>
                    <div class="mb-3">
                        <label for="car-brand" class="form-label">Марка автомобиля</label>
                        <input type="text" class="form-control" id="car-brand" name="car-brand"
                               placeholder="Введите модель автомобиля" value="{{ $car->carModel->carBrand->name }}">
                    </div>
                    <div class="mb-3">
                        <label for="car-model" class="form-label">Модель автомобиля</label>
                        <input type="text" class="form-control" id="car-model" name="car-model"
                               placeholder="Введите модель автомобиля" value="{{ $car->carModel->name }}">
                    </div>
                    <div class="mb-3">
                        <label for="year" class="form-label">Год выпуска</label>
                        <input type="number" class="form-control" id="year" name="year"
                               placeholder="Введите год выпуска" value="{{ $car->year }}">
                    </div>
                    <div class="mb-3">
                        <label for="mileage" class="form-label">Пробег</label>
                        <input type="number" class="form-control" id="mileage" name="mileage"
                               placeholder="Введите пробег" value="{{ $car->mileage }}">
                    </div>
                    <div class="mb-3">
                        <label for="color" class="form-label">Цвет автомобиля</label>
                        <input type="text" class="form-control" id="color" name="color"
                               placeholder="Введите цвет автомобиля" value="{{ $car->color }}">
                    </div>
                </fieldset>
            </form>
            <div class="col">
                <div class="">
                    <a class="btn btn-secondary mt-2" role="button"
                       href="{{ route('cars.edit', $car) }}">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
</div>
@include('components.footer')

resources/views/index.blade.php
@include('components.header')
<div class="p-4 m-4">
    <div class="body-container">
        <div class="container mb-5">
            <h1 class="display-6">Марки автомобилей</h1>
        </div>
        <div class="container">
            @include('components.messages')
            <div class="cars container overflow-hidden">
                @if($carBrands->isEmpty())
                    <p class="label-show">Марки автомобилей</p>
                @else
                    @foreach($carBrands as $carBrand)
                        <div class="card text-center mb-3">
                            <img src="/{{ $carBrand->name }}.jpg" class="card-img-top img-fluid" alt="...">
                            <div class="card-footer text-muted">
                                <h2 class="card-title">{{ $carBrand->name }}</h2>
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
        <div class="d-flex justify-content-center m-3">{!! $carBrands->links() !!}</div>
    </div>
</div>
@include('components.footer')